name: Create Release

   on:
     workflow_dispatch:
       inputs:
         version:
           description: 'Release version'
           required: true

   permissions:
     contents: write

   jobs:
     create-release:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             tag_name: v${{ github.event.inputs.version }}
             release_name: Release ${{ github.event.inputs.version }}
             draft: false
             prerelease: false
